#!/bin/bash

PATH_FILE=~/tools/cwd_tools/cwd-list.txt
RECENT_FILE=~/tools/cwd_tools/cwd-recent.txt

touch $PATH_FILE
touch $RECENT_FILE

cwd-get()
{
  if [ -z "$1" ]; then
    cd `sed -n 1p $PATH_FILE`
  else
    FOUND_PATH=`sed -n $1p $PATH_FILE`
    if [ -z "$FOUND_PATH" ]; then
      echo "No path found on line $1"
    else
      echo ${FOUND_PATH}
    fi
  fi
}

cwd-edit-tools(){
xdg-open ~/tools/cwd_tools/cwd_tools
}

cwd-paths()
{
  xdg-open $PATH_FILE
}

cwd-list() {
cat -n $PATH_FILE
}

cwd-add(){
if [ -z "$1" ]; then
  PWD= pwd
  echo $PWD >> $PATH_FILE
  echo "is added to cwd-list"
else
  if [ -d "$1" ]; then
    echo $1 >> $PATH_FILE
    echo "Path $1 is added to cwd-list"
  else
    echo "Path $1 is invalid"
  fi
fi
}


cwd-replace(){
echo "Not yet implemented"
}


cwd-remove()
{
  cwd-list
  echo "Which line number to be removed? "
  read num
  if ! [[ "$num" =~ ^[0-9]+$ ]]
  then
    echo "Only integer!"
    return
  fi
  #num=$(printf "%s" "$var"|tr -dc '[:digit:]')
  #num=$((var + 1))
  if [ -z "$num" ]; then
    echo "Add line number to remove"
  else
    FOUND_PATH=`sed -n ${num}p $PATH_FILE`
    if [ -z "$FOUND_PATH" ]; then
      echo "No path found on line $num"
    else
      sed -i -e ${num}d $PATH_FILE
      #NEW_FILE2=$(sed '/^\s*$/d' $NEW_FILE)
      echo "Removed path from line $num"
    fi
  fi
}

cwd()
{
  if [ "$1" = "l" ]
  then
    cwd-list
    return
  fi

  if [ "$1" = "a" ]
  then
    cwd-add
    return
  fi

  if [ "$1" = "r" ]
  then
    cwd-remove
    return
  fi

  if [ -z "$1" ]; then
    cd `sed -n 1p $RECENT_FILE`
  else
    FOUND_PATH=`sed -n $1p $PATH_FILE`
    if [ -z "$FOUND_PATH" ]; then
      echo "No path found on $1"
    else
      cd ${FOUND_PATH}
      echo $PWD > $RECENT_FILE
    fi
  fi
}
